<a href="https://colab.research.google.com/github/ViniciusBerti/20241_maua_ecm252_intro_git/blob/main/CD_P1_2025_IMPAR.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<head>
  <meta name="author" content="Rogério de Oliveira">
  <meta institution="author" content="ITM">
</head>

<img src="https://maua.br/images/selo-60-anos-maua.svg" width=300, align="right">
<!-- <h1 align=left><font size = 6, style="color:rgb(200,0,0)"> optional title </font></h1> -->

# **P1 - RA ÍMPAR**

In [1]:
#@markdown Nome completo e RA (*\<nome\>, \<RA\>*)
Aluno = 'Vinícius de Oliveira Berti, 21.01219-9' #@param {type:"string"}

In [3]:
path = 'https://github.com/Rogerio-mack/work/raw/main/data/'

# **Case**: Airbnb

Neste case, analise dados sobre imóveis alugados pela plataforma Airbnb em NYC no ano de 2019.

In [69]:
import pandas as pd
import numpy as np

df = pd.read_csv(path + 'AB_NYC_2019.csv')
df

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,20913,Charming 1 bed GR8 WBurg LOCATION!,79402,Christiana,Brooklyn,Williamsburg,40.70984,-73.95775,Entire home/apt,100,5,168,2018-07-22,1.57,1,0
1,25235,Large 2 Bedroom Great for Groups!,87773,Shelly,Brooklyn,Bedford-Stuyvesant,40.68373,-73.92377,Entire home/apt,125,90,162,2019-06-28,1.46,2,137
2,76761,Eveland the Place to Stay & Enjoy a 5-⭐️ 2bdrm,118971,Evelyn,Brooklyn,South Slope,40.66552,-73.99019,Entire home/apt,169,2,398,2019-06-28,3.97,3,182
3,135465,Garden apartment close to Manhattan,663879,Christopher,Brooklyn,Fort Greene,40.68626,-73.97598,Entire home/apt,170,3,86,2019-06-20,0.91,2,286
4,169002,Modern Space in Charming Pre-war,805344,Alec,Manhattan,Harlem,40.82411,-73.94934,Private room,65,2,41,2019-06-16,0.43,2,59
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
799,36413779,Sunny & spacious room in a 3 Br - Williamsburg,2449230,Itamar,Brooklyn,Williamsburg,40.71812,-73.95495,Private room,80,5,0,NaN,NaN,1,38
800,36421287,Nice & Lovely room in LIC.5 stops to Times Square,203866020,Karma,Queens,Sunnyside,40.73799,-73.92749,Private room,60,1,0,NaN,NaN,1,34
801,36439512,The Bushwick Backhouse Loft.,180336853,Dash,Brooklyn,Bushwick,40.70470,-73.92250,Private room,70,2,0,NaN,NaN,1,255
802,36452721,Massage Spa. Stay overnight. Authors Artist dr...,274079964,Richard,Brooklyn,Sheepshead Bay,40.59866,-73.95661,Private room,800,1,0,NaN,NaN,1,23
803,36472171,1 bedroom in sunlit apartment,99144947,Brenda,Manhattan,Inwood,40.86845,-73.92449,Private room,80,1,0,NaN,NaN,1,79

# Q1. Proprietários com mais imóveis na plataforma

Obtenha os 3 proprietários ("hosts") com mais imóveis sendo anunciados na plataforma, e a respectiva quantidade de imóveis anunciados.

In [68]:
host_counts = df.groupby('host_id')['id'].count().reset_index()
host_counts.columns = ['host_id', 'number_of_listings']
host_counts = host_counts.sort_values('number_of_listings', ascending=False)
top_hosts = pd.merge(host_counts.head(3), df[['host_id', 'host_name']], on='host_id', how='left')
top_hosts = top_hosts.drop_duplicates(subset=['host_id', 'host_name'])

print(top_hosts[['host_name', 'number_of_listings']])

       host_name  number_of_listings
0   Sonder (NYC)                   7
7           Kara                   4
11       Stanley                   4

# Q2B. Preço nos bairros com mais imóveis

 Qual o preço médio dos imóveis, considerando somente os preços dos imóveis cujos bairros (`neighbourhood`) tenham mais de 20 imóveis sendo anunciados?

In [17]:
bairros_contagem = df['neighbourhood'].value_counts()
bairros_validos = bairros_contagem[bairros_contagem > 20].index
df_filtrado = df[df['neighbourhood'].isin(bairros_validos)]
preco_medio = df_filtrado['price'].mean()

print(f'O preço médio dos imóveis em bairros com mais de 20 anúncios é: USD {preco_medio:.2f}')

O preço médio dos imóveis em bairros com mais de 20 anúncios é: USD 151.42

# Q3B.  Brooklyn *outliers*

Qual o percentual de imóveis de Manhattan com preços estatisticamente discrepantes (*outliers*) com relação aos preços de todos os imóveis?

In [28]:
brooklyn = df[df['neighbourhood_group'] == 'Brooklyn']

q1 = brooklyn['price'].quantile(0.25)
q3 = brooklyn['price'].quantile(0.75)
iqr = q3 - q1

limite_inferior = q1 - 1.5 * iqr
limite_superior = q3 + 1.5 * iqr

outliers = brooklyn[(brooklyn['price'] < limite_inferior) | (brooklyn['price'] > limite_superior)]

perc_brooklyn = (len(outliers) / len(brooklyn)) * 100

print(f'Percentuais de outliers de preços, Brooklyn: {perc_brooklyn:.2f} %')

Percentuais de outliers de preços, Brooklyn: 5.76 %

# Q4B. Scores

Nesta tarefa você deve atribuir a cada imóvel um valor de *score* (`df['score']`) baseado nas seguintes regras:

1. Imóveis com `availability_365` > 90 recebem +10 pontos enquanto imóveis com `availability_365` < 5 recebem -5 pontos;
2. Imóveis com o número de reviews >= 10 recebem +5 pontos para cada 10 reviews (por ex. se número de reviews = 20, são atribuídos +10 pontos). Se número de reviews = 0 o imóvel recebe -5 pontos;
3. Imóveis com preço abaixo da média de seu `neighbourhood`	recebem +5 pontos.

Implemente empregando `apply()` ou um laço de programa, como preferir.

In [30]:
preco_medio_bairro = df.groupby('neighbourhood')['price'].mean()

def calcular_score(x):
    score = 0

    if x['availability_365'] > 90:
        score += 10
    elif x['availability_365'] < 5:
        score -= 5

    if x['number_of_reviews'] == 0:
        score -= 5
    else:
        score += (x['number_of_reviews'] // 10) * 5

    media_bairro = preco_medio_bairro.get(x['neighbourhood'], None)
    if media_bairro and x['price'] < media_bairro:
        score += 5

    return score

df['score'] = df.apply(calcular_score, axis=1)

print(f'A soma dos valores de score é: ', df['score'].sum())

A soma dos valores de score é:  10955

# Q5. Enriquecendo os dados

Enriqueça os dados dos imóveis com os valores dos impostos e multas municipais. Cacule a média de impostos e multas de cada grupo de vizinhaça, `neighbourhood_group`. Note que existem imóveis sem impostos e sem multas, esses são imóveis isentos, mas devem ser considerados nos cálculos de média (por exemplo, você pode considerar esses imóveis com valor 0).

In [43]:
df_taxes = pd.read_csv(path + 'AB_NYC_2019_taxes.csv')
df_taxes

            id   type   value
0     35907127  taxes  1315.0
1       804815  taxes     NaN
2     22328585  taxes   900.0
3     27876600  taxes   869.0
4     34976037  taxes  1629.0
...        ...    ...     ...
1523  34284316  fines     NaN
1524  20325804  fines     NaN
1525  25872986  fines     NaN
1526  19365218  fines   906.0
1527   4235843  fines     NaN

[1528 rows x 3 columns]

In [54]:
df_taxes_pivotado = df_taxes.pivot_table(index='id', columns='type', values='value', aggfunc='sum')
df_taxes_pivotado = df_taxes_pivotado.reset_index()
df_taxes_pivotado = df_taxes_pivotado.fillna(0)

df_completo = df.merge(df_taxes_pivotado, how='left', on='id')
df_completo[['fines', 'taxes']] = df_completo[['fines', 'taxes']].fillna(0)
medias = df_completo.groupby('neighbourhood_group')[['fines', 'taxes']].mean()

print("Média de multas e impostos por neighbourhood_group:")
print(medias.round(2))

Média de multas e impostos por neighbourhood_group:
                      fines    taxes
neighbourhood_group
Bronx                126.06   848.26
Brooklyn             313.01   854.28
Manhattan            314.20   886.65
Queens               322.51   803.52
Staten Island        575.34  1145.57

# Q6. Quebras

Construa no `Pandas` um "relatório" (`df_report`) como abaixo. Os valores são ordenados `neighbourhood_group`,`neighbourhood`. Cada "página" contém apenas 30 linhas. A cada "quebra" de `neighbourhood_group` é gerada uma linha com preço médio do `neighbourhood_group` e, então, é iniciada uma nova página.

O item `line_id` é opcional mas deve auxiliá-lo nessa tarefa.

Ao final produza a soma dos preços das páginas abaixo...

In [70]:
sum_price_pages = df_report[ df_report.page_id.isin([1,24,25,26,28]) ].groupby('page_id').price.sum().astype(int).sum()

print(f'A soma dos preços das páginas 1, 24, 25 e 28 é: {sum_price_pages}')

A soma dos preços das páginas 1, 24, 25 e 28 é: 17838

#### Aqui um *sample* do report.

In [75]:
df_report.iloc[-10::,:]

     line_id  page_id neighbourhood_group  neighbourhood       price
799      799       29              Queens       Woodside  120.000000
800      800       29              Queens           MEAN   92.227848
801      801       30       Staten Island  Arden Heights   83.000000
802      802       30       Staten Island  Randall Manor   99.000000
803      803       30       Staten Island    South Beach   20.000000
804      804       30       Staten Island    South Beach  100.000000
805      805       30       Staten Island     St. George  130.000000
806      806       30       Staten Island      Todt Hill  135.000000
807      807       30       Staten Island  Tompkinsville   59.000000
808      808       30       Staten Island           MEAN   89.428571

In [74]:
df_sorted = df.sort_values(['neighbourhood_group', 'neighbourhood']).reset_index(drop=True)

linhas = []

line_id = 0
page_id = 1
linhas_na_pagina = 0
grupo_anterior = None

for _, row in df_sorted.iterrows():
    grupo_atual = row['neighbourhood_group']

    if grupo_atual != grupo_anterior and grupo_anterior is not None:
        media_preco = df_sorted[df_sorted['neighbourhood_group'] == grupo_anterior]['price'].mean()
        linhas.append({
            'neighbourhood_group': grupo_anterior,
            'neighbourhood': 'MEAN',
            'price': media_preco,
            'page_id': page_id,
            'line_id': line_id
        })
        line_id += 1
        linhas_na_pagina += 1

        if linhas_na_pagina >= 30:
            page_id += 1
            linhas_na_pagina = 0
        else:
            page_id += 1
            linhas_na_pagina = 0

    linhas.append({
        'line_id': line_id,
        'page_id': page_id,
        'neighbourhood_group': grupo_atual,
        'neighbourhood': row['neighbourhood'],
        'price': row['price']
    })
    line_id += 1
    linhas_na_pagina += 1

    if linhas_na_pagina >= 30:
        page_id += 1
        linhas_na_pagina = 0

    grupo_anterior = grupo_atual

if grupo_anterior is not None:
    media_preco = df_sorted[df_sorted['neighbourhood_group'] == grupo_anterior]['price'].mean()
    linhas.append({
        'line_id': line_id,
        'page_id': page_id,
        'neighbourhood_group': grupo_anterior,
        'neighbourhood': 'MEAN',
        'price': media_preco
    })

df_report = pd.DataFrame(linhas)

sum_price_pages = df_report[df_report.page_id.isin([1,24,25,26,28])].groupby('page_id')['price'].sum().astype(int).sum()

print(f'A soma dos preços das páginas 1, 24, 25 e 28 é: {sum_price_pages}')

A soma dos preços das páginas 1, 24, 25 e 28 é: 17838